server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
ribbon:
  # Feign通过ribbon设置超时时长
  ReadTimeout: 5000
  ConnectTimeout: 5000
logging:
  level:
    per.neal.learn.service.PaymentFeignService: debug