server:
  port: 8002

spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&charcterEncoding=utf-8&useSSL=false
    username: root
    password: 7758258a

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: per.neal.learn.entities
eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    # 是否暴露主机名、IP
    instance-id: payment8002
    prefer-ip-address: false